name: Codecov Integration

on: [push, pull_request]

jobs:
  unit_test_coverage:
    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}